const data = {
  people: [
    {
      id: 27411,
      created: "2025-04-28T18:50:46Z",
      updated: "2025-05-27T09:05:39Z",
      createdVia: "API",
      lastActivity: "2025-06-16T12:01:12Z",
      name: "Liantsoa",
      firstName: "Liantsoa",
      lastName: "",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Ylopo",
      sourceId: 107,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/061e7bf7-e4a8-43ad-8ce0-972a52c8ae4d",
      leadFlowId: 36,
      delayed: false,
      contacted: 0,
      price: 1019000,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 18,
      assignedPondId: null,
      assignedTo: "Randy Molnar",
      tags: [
        "Re-engage",
        "Buyer",
        "AI_NOT_INTERESTED",
        "YLOPO_ORGANIC",
        "Halton Hills",
        "sell_before_buy=No",
        "preapproved_for_loan=No",
        "timeline=within 90 days",
        "Randy Molnar - Real Estate Services",
        "do_you_own_a_home=No",
        "Ylopo_Rmolnar",
        "AI_VOICE_NEEDS_FOLLOW_UP",
        "New",
        "2025",
        "appointment_not booked",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "hariandra@hotmail.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "5147275159",
          type: "mobile",
          status: "Invalid",
          isPrimary: 1,
          normalized: "5147275159",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 1,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 18,
          name: "Randy Molnar",
          assigned: true,
          role: "Agent",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27401,
      created: "2025-04-23T08:03:38Z",
      updated: "2025-07-01T14:10:45Z",
      createdVia: "API",
      lastActivity: "2025-07-01T14:10:45Z",
      name: "No name",
      firstName: "No name",
      lastName: "",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "mark.thejensenteam.ca",
      sourceId: 277,
      sourceUrl: "",
      leadFlowId: 59,
      delayed: false,
      contacted: 0,
      price: null,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 1,
      assignedPondId: null,
      assignedTo: "Mark Jensen",
      tags: [
        "Bad_Number",
        "BAD_PHONE",
        "AI_NOT_INTERESTED",
        "Burlington",
        "Oakville",
        "appointment_not booked",
        "Mod_Ai",
      ],
      emails: [],
      phones: [
        {
          value: "(437) 428-1078",
          type: "mobile",
          status: "Invalid",
          isPrimary: 1,
          normalized: "4374281078",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 0,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 1,
          name: "Mark Jensen",
          assigned: true,
          role: "Broker",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27319,
      created: "2025-03-29T17:44:50Z",
      updated: "2025-06-28T19:15:44Z",
      createdVia: "API",
      lastActivity: "2025-06-29T16:07:12Z",
      name: "Lubna Chaudhry",
      firstName: "Lubna",
      lastName: "Chaudhry",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "search.thejensenteam.ca",
      sourceId: 278,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/2231675f-a9bd-422b-83ad-3c74377e61c0",
      leadFlowId: 60,
      delayed: false,
      contacted: 1,
      price: 1199000,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 1,
      assignedPondId: null,
      assignedTo: "Mark Jensen",
      tags: [
        "Milton",
        "YPRIORITY",
        "RETURNED",
        "LISTING_ALERT_SUNSET",
        "YLOPO_FACEBOOK",
        "NEXT_6_MONTHS",
        "I_M_ON_A_TIMELINE_TO_MOVE",
        "Remarketing Visitor",
        "NEW_NUMBER",
        "AI_Call",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "lubnac70@hotmail.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "6477462625",
          type: "Primary (Ylopo)",
          status: "Valid",
          isPrimary: 1,
          normalized: "6477462625",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 6,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 1,
          name: "Mark Jensen",
          assigned: true,
          role: "Broker",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27298,
      created: "2025-03-23T20:39:45Z",
      updated: "2025-06-05T09:07:55Z",
      createdVia: "API",
      lastActivity: "2025-06-06T13:14:06Z",
      name: "Rick",
      firstName: "Rick",
      lastName: "",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Ylopo",
      sourceId: 107,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/543d2b04-5ab0-4a47-8898-5dbe38af789e",
      leadFlowId: 36,
      delayed: false,
      contacted: 0,
      price: 1750000,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 18,
      assignedPondId: null,
      assignedTo: "Randy Molnar",
      tags: [
        "Re-engage",
        "Buyer",
        "Bounced",
        "RETURNED",
        "LISTING_ALERT_SUNSET",
        "YLOPO_FACEBOOK",
        "Remarketing Visitor",
        "Erin",
        "Randy Molnar - Real Estate Services",
        "Ylopo_Rmolnar",
        "Y_HOME_3_VIEW",
        "New",
        "2025",
        "New Lead",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "rick456@yahoo.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "4166359634",
          type: "mobile",
          status: "Invalid",
          isPrimary: 1,
          normalized: "4166359634",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 2,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 18,
          name: "Randy Molnar",
          assigned: true,
          role: "Agent",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27274,
      created: "2025-03-13T17:32:24Z",
      updated: "2025-05-24T05:06:04Z",
      createdVia: "API",
      lastActivity: "2025-05-24T05:06:04Z",
      name: "Mitchell Plant",
      firstName: "Mitchell",
      lastName: "Plant",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Realty AI",
      sourceId: 261,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/4a6300b7-85ce-477d-abc4-dda52722245d",
      leadFlowId: 51,
      delayed: false,
      contacted: 0,
      price: 1229000,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 1,
      assignedPondId: null,
      assignedTo: "Mark Jensen",
      tags: [
        "BAD_PHONE",
        "Bounced",
        "LISTING_ALERT_UNSUB",
        "Y_IMPORT",
        "RETURNED",
        "Oakville",
        "NEW_NUMBER",
        "MANUAL",
        "Lead-Day1-15-Audit",
        "Mark_Jensen",
        "New",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "mitch.plant@hotmail.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "4162314545",
          type: "Primary (Ylopo)",
          status: "Invalid",
          isPrimary: 1,
          normalized: "4162314545",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 3,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 1,
          name: "Mark Jensen",
          assigned: true,
          role: "Broker",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27269,
      created: "2025-03-12T15:19:07Z",
      updated: "2025-05-24T05:06:03Z",
      createdVia: "API",
      lastActivity: "2025-05-24T05:06:03Z",
      name: "Hubert Graham",
      firstName: "Hubert",
      lastName: "Graham",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Facebook",
      sourceId: 43,
      sourceUrl: "",
      leadFlowId: 49,
      delayed: false,
      contacted: 0,
      price: null,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 18,
      assignedPondId: null,
      assignedTo: "Randy Molnar",
      tags: [
        "Randy Molnar - Real Estate Services",
        "Ylopo_Rmolnar",
        "2024",
        "AI_VOICE_NEEDS_FOLLOW_UP",
        "New",
        "Alistair buyer lead-copy",
        "Living in Halton Hills",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "hubertgraham747@gmail.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "647",
          type: "mobile",
          status: "Invalid",
          isPrimary: 1,
          normalized: "647",
          isLandline: null,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 0,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 18,
          name: "Randy Molnar",
          assigned: true,
          role: "Agent",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27188,
      created: "2025-02-15T15:11:00Z",
      updated: "2025-05-24T05:05:55Z",
      createdVia: "API",
      lastActivity: "2025-06-14T13:14:29Z",
      name: "Nwamaka Agu",
      firstName: "Nwamaka",
      lastName: "Agu",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Direct Connect PPC",
      sourceId: 263,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/3072a5a3-3279-4532-aac4-c8774eafdab5",
      leadFlowId: 53,
      delayed: false,
      contacted: 0,
      price: 834900,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 18,
      assignedPondId: null,
      assignedTo: "Randy Molnar",
      tags: [
        "Milton",
        "Buyer",
        "AI_NOT_INTERESTED",
        "RETURNED",
        "YLOPO_ADWORDS",
        "NEW_NUMBER",
        "sell_before_buy=No",
        "YLOPO_DIRECT_CONNECT_PPC",
        "call_about_homes=yes",
        "call_now=another_time",
        "Randy Molnar - Real Estate Services",
        "Ylopo_Rmolnar",
        "2024",
        "Y_HOME_3_VIEW",
        "timeline=More than 6 months",
        "New",
        "Long Term Nuture Action Plan",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "jusremedium@yahoo.ca",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "2265079308",
          type: "Primary (Ylopo)",
          status: "Invalid",
          isPrimary: 1,
          normalized: "2265079308",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 11,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 18,
          name: "Randy Molnar",
          assigned: true,
          role: "Agent",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27144,
      created: "2025-01-30T06:26:12Z",
      updated: "2025-07-03T09:11:39Z",
      createdVia: "API",
      lastActivity: "2025-07-03T12:03:02Z",
      name: "Marsilda Xhemali",
      firstName: "Marsilda",
      lastName: "Xhemali",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Ylopo",
      sourceId: 107,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/9ee060b4-843b-4204-bce9-81e93a505ebc",
      leadFlowId: 36,
      delayed: false,
      contacted: 0,
      price: 2395000,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 1,
      assignedPondId: null,
      assignedTo: "Mark Jensen",
      tags: [
        "Buyer",
        "YPRIORITY",
        "AI_NEEDS_FOLLOW_UP",
        "Bounced",
        "RETURNED",
        "Burlington",
        "YLOPO_ADWORDS",
        "DYNAMIC_REG_ADDRESS",
        "NEW_NUMBER",
        "sell_before_buy=No",
        "preapproved_for_loan=No",
        "Lead-Day1-15-Audit",
        "timeline=over 6 months",
        "do_you_own_a_home=No",
        "LCADrip",
        "Retell-List1",
        "AI_Call",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "marsildaxhemali@hotmail.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "9056174878",
          type: "mobile",
          status: "Valid",
          isPrimary: 1,
          normalized: "9056174878",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 2,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 1,
          name: "Mark Jensen",
          assigned: true,
          role: "Broker",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27125,
      created: "2025-01-22T01:24:25Z",
      updated: "2025-05-24T05:05:37Z",
      createdVia: "API",
      lastActivity: "2025-05-24T05:05:37Z",
      name: "Jenna Ortega",
      firstName: "Jenna",
      lastName: "Ortega",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Ylopo",
      sourceId: 107,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/784c43f3-9387-4524-ad29-3fe4f9ed69e6",
      leadFlowId: 36,
      delayed: false,
      contacted: 0,
      price: 3788800,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 1,
      assignedPondId: null,
      assignedTo: "Mark Jensen",
      tags: [
        "BAD_PHONE",
        "Buyer",
        "Oakville",
        "DYNAMIC_REG_ADDRESS",
        "sell_before_buy=No",
        "preapproved_for_loan=No",
        "timeline=over 6 months",
        "do_you_own_a_home=No",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "jenna.ortega@gmail.com",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "5162553542",
          type: "landline",
          status: "Invalid",
          isPrimary: 1,
          normalized: "5162553542",
          isLandline: true,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: {
        name: "Jenna Ortega",
        firstName: "Jenna",
        lastName: "Ortega",
        gender: "Female",
        age: "35",
        location: "San Jose, CA, United States",
        company: "Kg Online Marketing",
        title: "Human Resource Executive",
        bio: "- Involving in the resource hunting and recruitment process of an individual.- Identifying and verifying the documentation of the staff for the recruitment process.- Maintaining the records of an employee details.- Gathering information from other departments and employees.- Arranging the various training and development programs.- Providing the coaching and training to the employees.- Ensuring about the employee safety, security, welfare, wellness and health.",
        topics: "",
        facebook: "",
        twitter: "",
        googleProfile: "",
        googlePlus: "",
        linkedIn: "https://www.linkedin.com/in/jenna-ortega-319aa9bb",
      },
      websiteVisits: 1,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 1,
          name: "Mark Jensen",
          assigned: true,
          role: "Broker",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
    {
      id: 27122,
      created: "2025-01-21T12:13:06Z",
      updated: "2025-05-24T05:05:37Z",
      createdVia: "API",
      lastActivity: "2025-05-24T05:05:37Z",
      name: "M",
      firstName: "M",
      lastName: "",
      stage: "Bad Phone Number",
      stageId: 26,
      source: "Direct Connect PPC",
      sourceId: 263,
      sourceUrl:
        "https://stars.ylopo.com/lead-detail/6757fc28-03a9-4544-9d70-7ac0d89f99f1",
      leadFlowId: 53,
      delayed: false,
      contacted: 1,
      price: 1169000,
      assignedLenderId: null,
      assignedLenderName: null,
      assignedUserId: 18,
      assignedPondId: null,
      assignedTo: "Randy Molnar",
      tags: [
        "Buyer",
        "AI_NOT_INTERESTED",
        "RETURNED",
        "YPRIORITY_OPT_OUT",
        "Unsubscribed",
        "YLOPO_ADWORDS",
        "Georgetown",
        "sell_before_buy=No",
        "preapproved_for_loan=No",
        "Erin",
        "YLOPO_DIRECT_CONNECT_PPC",
        "Whitchurch-Stouffville",
        "call_now=another_time",
        "Randy Molnar - Real Estate Services",
        "Ylopo_Rmolnar",
        "2024",
        "Y_FAVORITED_LISTING",
        "call_about_homes=I'm looking for something else",
        "timeline=Now",
        "Long Term Nuture Action Plan",
        "Mod_Ai",
      ],
      emails: [
        {
          value: "hadallerm@csviamonde.net",
          type: "home",
          status: "Valid",
          isPrimary: 1,
        },
      ],
      phones: [
        {
          value: "4165003280",
          type: "mobile",
          status: "Invalid",
          isPrimary: 1,
          normalized: "4165003280",
          isLandline: false,
          isOnboardingNumber: false,
        },
      ],
      addresses: [],
      picture: null,
      socialData: [],
      websiteVisits: 3,
      timeframeId: null,
      timeframeUpdated: null,
      timeframeStatus: null,
      timeframeDateRange: null,
      claimed: true,
      dealStatus: null,
      dealStage: null,
      dealName: null,
      dealCloseDate: null,
      dealPrice: null,
      firstToClaimOffer: false,
      collaborators: [
        {
          id: 18,
          name: "Randy Molnar",
          assigned: true,
          role: "Agent",
        },
      ],
      teamLeaders: [],
      pondMembers: [],
    },
  ],
};

export default data;
