# Generated by Django 5.2.4 on 2025-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp_user_otp_type_user_resetpasswordexpires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
