# Generated by Django 5.2.4 on 2025-07-05 12:44

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_weekly_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weekly_schedule',
            field=models.JSONField(default=users.models.default_weekly_schedule),
        ),
    ]
